### ISSUE TITLE
Other models

### ISSUE THREAD

**Issue by abstractpoint** [azya52/Seiko#2]
Amazing work, well done. Excited to see these vintage devices live on like this.

I was looking around and other more abundant model is U-3000. Is there a chance these are also flashable? My ultimate dream is to run assembly or basic on these. Thanks!

**Comment by azya52** [comment]
Sorry, I just saw the message.
Unfortunately, most likely it is impossible. I have a Seiko Memo Diary, they apparently have the same functions as the UC-3000, and I could not load programs on them.

**Comment by synthead** [comment]
Interesting! What did you observe when you could not load programs onto them?

**Comment by azya52** [comment]
[synthead](https://github.com/synthead), nothing happens when you try to send the program. Actually, I've already got the UC-3000 firmware for the [emulator](https://github.com/azya52/Emulator2000#readme), and there doesn't seem to be any way to execute third party code (although I haven't explored that side much).
